int check_first_last(int n, char *s, int len);
int is_palindrome(char *s);
int count_a(int x, int a, int b);
int count_b(int x, int a, int b);
int is_prime_number(int n);
int count_up_recursively(int a, int b);
int _sqrt_recursion(int n);
int _pow_recursion(int x, int y);
int factorial(int n);
int _strlen_recursion(char *s);
int _strlen_recursion(char *s);
void _print_rev_recursion(char *s);
int _putchar(char c);
void _puts_recursion(char *s);
